name: test_aughovernet
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11.11
  - pip=24.1.2
  - openslide
  - pip:
    - -r /home/jenny/Hover/aug_hover_net_fork/CONIC_Pathology_AI/requirements.txt
    - openslide-python
